# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Leetmate < Formula
  desc "不给答案，只给提示——终端里的 LeetCode 辅导 + 间隔复习工具"
  homepage "https://github.com/DuckInAShirt/leetmate"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DuckInAShirt/leetmate/releases/download/v0.1.0/leetmate_0.1.0_macOS_amd64.tar.gz"
      sha256 "10ddfc2c989402e57ffc242ca16f9d82b0c0014d174f92c7fac9f4e6d63f9668"

      define_method(:install) do
        bin.install "leetmate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DuckInAShirt/leetmate/releases/download/v0.1.0/leetmate_0.1.0_macOS_arm64.tar.gz"
      sha256 "457229f5c66a7bc7e9f5e7fbbdafa220c85425f7b1c9f43981a5bebebbd1513d"

      define_method(:install) do
        bin.install "leetmate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DuckInAShirt/leetmate/releases/download/v0.1.0/leetmate_0.1.0_linux_amd64.tar.gz"
      sha256 "7f01169f76297416ea45975660ee1f09563e9be6e74a0f06dcf60b7df947a0bc"
      define_method(:install) do
        bin.install "leetmate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DuckInAShirt/leetmate/releases/download/v0.1.0/leetmate_0.1.0_linux_arm64.tar.gz"
      sha256 "876bfe6fbf3b93d89ea646b15165997ed0bfc5ce53a266cc1e010b1dc19f6a0a"
      define_method(:install) do
        bin.install "leetmate"
      end
    end
  end

  test do
    system "#{bin}/leetmate", "--version"
  end
end
